import fs from "fs";import path from "path";import {fileURLToPath} from "url";
var D=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../public/data");
function p(a){return a[Math.floor(Math.random()*a.length)]}
function pn(a,n){var s=new Set();while(s.size<n&&s.size<a.length)s.add(p(a));return[...s]}
var df=["easy","medium","hard"];
var ts="SRE DevOps observability monitoring log metric trace trace span TraceId metrics logs Prometheus Grafana OpenTelemetry Exporter Alertmanager Dashboard QPS TPS RT P95 P99 error rate availability saturation CPU memory disk network RED method USE method SLI SLO SLA error budget alert alert fatigue alert convergence on-call runbook playbook fault diagnosis emergency response incident severity MTTR MTBF RCA root cause analysis capacity planning load test performance bottleneck circuit breaker rate limiting degradation grayscale release blue-green release rollback change management stability culture incident management postmortem chaos engineering resilience testing canary release feature flag service level objective error budget policy burn rate alerting strategy threshold anomaly detection trend analysis historical baseline capacity model scalability plan database connection pool optimization code profiling flame graph continuous profiling incident commander war room status page outage communication feedback loop learning culture error budget policy golden signals four golden signals latency traffic errors saturation";
var t=ts.trim().split(/\s+/).filter(Boolean);
function bt(){return t.map(function(n,i){return{id:"sr-tag-"+String(i+1).padStart(3,"0"),name:n,category:"SRE",description:"SRE标签:"+n,count:0,createdAt:"2026-07-03T00:00:00.000Z"};});}
var CD=[
  {id:"sr-course-01",order:1,slug:"SRE入门",title:"SRE与线上稳定性入门",description:"SRE定义、核心原则、学习路线。",estimatedHours:4,diff:"easy"},
  {id:"sr-course-02",order:2,slug:"三大支柱",title:"可观测性三大支柱：日志、指标、追踪",description:"Logs/Metrics/Traces三大支柱作用与工具。",estimatedHours:8,diff:"easy"},
  {id:"sr-course-03",order:3,slug:"监控指标",title:"监控指标体系与服务健康度",description:"RED方法、USE方法、黄金信号、四大指标。",estimatedHours:8,diff:"medium"},
  {id:"sr-course-04",order:4,slug:"Prometheus",title:"Prometheus入门与指标采集",description:"PromQL、Exporter、Pull模型、指标类型。",estimatedHours:10,diff:"medium"},
  {id:"sr-course-05",order:5,slug:"Grafana看板",title:"Grafana看板设计",description:"Dashboard设计、数据源配置、变量模板、告警。",estimatedHours:8,diff:"medium"},
  {id:"sr-course-06",order:6,slug:"日志系统",title:"日志系统、结构化日志与日志检索",description:"结构化日志、ELK/Loki、日志检索、日志分析。",estimatedHours:8,diff:"hard"},
  {id:"sr-course-07",order:7,slug:"链路追踪",title:"链路追踪、TraceId与OpenTelemetry",description:"OpenTelemetry、Trace/Span、采样、传播。",estimatedHours:10,diff:"hard"},
  {id:"sr-course-08",order:8,slug:"告警规则",title:"告警规则、告警收敛与值班机制",description:"Alertmanager、告警规则、沉默、抑制、On-call。",estimatedHours:8,diff:"hard"},
  {id:"sr-course-09",order:9,slug:"SLOSLA",title:"SLI、SLO、SLA与错误预算",description:"SLI定义、SLO目标、SLA承诺、错误预算策略。",estimatedHours:10,diff:"hard"},
  {id:"sr-course-10",order:10,slug:"故障排查",title:"故障定位、排查流程与应急响应",description:"故障等级、排查流程、MTTR、RCA。",estimatedHours:10,diff:"hard"},
  {id:"sr-course-11",order:11,slug:"容量规划",title:"容量规划、压测与性能分析",description:"容量模型、压测工具、性能分析、限流降级。",estimatedHours:8,diff:"hard"},
  {id:"sr-course-12",order:12,slug:"发布稳定性",title:"发布稳定性、灰度、回滚与变更管理",description:"灰度发布、蓝绿部署、回滚、变更评审。",estimatedHours:8,diff:"hard"},
  {id:"sr-course-13",order:13,slug:"事故复盘",title:"事故复盘、稳定性治理与工程文化",description:"事后复盘、改进措施、稳定性文化。",estimatedHours:8,diff:"hard"},
  {id:"sr-course-14",order:14,slug:"SRE项目面试",title:"SRE综合项目、面试与实战训练",description:"完整SRE体系、面试题、故障模拟。",estimatedHours:8,diff:"hard"},
];
function bc(){return CD.map(function(c){return{id:c.id,order:c.order,slug:c.slug,title:c.title,description:c.description,estimatedHours:c.estimatedHours,difficulty:c.diff,tags:[c.title],lessonIds:[],totalLessons:0,totalQuestions:0,prerequisites:[],outcomes:["理解SRE理念","能设计监控体系","会故障排查","掌握稳定性工程"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
function bl(){var all=[];var id=1;function add(ci,t2){var n=String(id).padStart(3,"0");all.push({id:"sr-lesson-"+n,courseId:CD[ci].id,order:all.filter(function(l){return l.courseId===CD[ci].id}).length+1,title:t2,slug:t2.replace(/[\s，。、：；（）\-+]+/g,"-").replace(/-+/g,"-"),summary:t2,content:"# "+t2+"\n\n"+t2+"内容。",contentFormat:"markdown",estimatedMinutes:30,difficulty:id<60?"easy":id<130?"medium":"hard",knowledgePointIds:[],practiceQuestionIds:[],tags:["SRE"],prerequisites:[],updatedAt:"2026-07-03T00:00:00.000Z"});id++;}
  for(var ci=0;ci<14;ci++)for(var j=0;j<13;j++)add(ci,"SRE课程"+(ci+1)+"章"+(j+1));return all;}
var KPN=[["SRE","站点可靠性"],["可观测性","系统可见"],["Prometheus","监控系统"],["Grafana","看板工具"],["OpenTelemetry","遥测标准"],["SLI","服务指标"],["SLO","服务目标"],["SLA","服务协议"],["错误预算","容错预算"],["告警","异常通知"],["On-call","值班机制"],["MTTR","恢复时间"],["RCA","根因分析"],["容量规划","资源规划"],["灰度发布","逐步发布"]];
function bk(){var k=[];for(var i=0;i<KPN.length;i++){k.push({id:"sr-kp-"+String(i+1).padStart(4,"0"),name:KPN[i][0],description:KPN[i][1],category:"SRE",tags:["SRE"],difficulty:i<8?"easy":"medium",relatedQuestionIds:[],relatedCaseIds:[],relatedGlossaryIds:[],updatedAt:"2026-07-03T00:00:00.000Z"});}for(var i=0;i<720;i++){k.push({id:"sr-kp-"+String(k.length+1).padStart(4,"0"),name:"SRE概念"+(k.length+1),description:"SRE概念",category:"SRE",tags:["SRE"],difficulty:"hard",relatedQuestionIds:[],relatedCaseIds:[],relatedGlossaryIds:[],updatedAt:"2026-07-03T00:00:00.000Z"});}return k;}
var QC=["SRE入门","三大支柱","监控指标","Prometheus","Grafana看板","日志系统","链路追踪","告警规则","SLOSLA","故障排查","容量规划","发布稳定性","事故复盘","SRE项目面试"];
function bq(){
  var qs=[];var qid=1;
  var t2=[[0,"SRE含义？",["站点可靠性工程","软件工程","安全","开发"],"A","easy"],[1,"可观测性三大支柱？",["日志/指标/追踪","日志/告警/监控","指标/看板/告警","QPS/延迟/错误"],"A","easy"],[3,"PromQL用于？",["查询Prometheus指标","查询数据库","查询日志","查询链追踪"],"A","medium"],[5,"结构化日志好处？",["便于检索和分析","占用更少空间","更美观","更安全"],"A","medium"],[6,"TraceId传播方式？",["HTTP Header","Cookie","Body","URL参数"],"A","medium"],[7,"Alertmanager支持？",["分组/抑制/沉默","只告警","只恢复","只记录"],"A","hard"],[8,"SLO是？",["服务等级目标","服务等级协议","服务等级指标","错误预算"],"A","hard"],[9,"MTTR含义？",["平均恢复时间","平均故障间隔","平均检测时间","平均响应时间"],"A","hard"],[10,"容量规划基础？",["历史数据和业务增长","随机猜测","最大配置","最小资源"],"A","hard"],[12,"事故复盘目的？",["改进系统防止再发生","追责","惩罚","记录"],"A","hard"]];
  for(var i=0;i<t2.length;i++){var t_=t2[i];if(t_[4]&&typeof t_[4]==="string"&&t_[4].includes(":"))t_[4]=t_[4].replace(":","");qs.push({id:"sr-q-"+String(qid).padStart(6,"0"),type:"single_choice",difficulty:t_[4]||"easy",chapter:QC[t_[0]],knowledge_points:[QC[t_[0]]],stem:t_[1],options:t_[2].map(function(x,j){return{label:String.fromCharCode(65+j),text:x};}),answer:t_[3],explanation:t_[1]+"正确"+t_[3]+"。",wrong_reason:"加强。",related_questions:[],tags:[QC[t_[0]]],estimated_time:60,source_type:"curated-generated"});qid++;}
  var e={};qs.forEach(function(q){e[q.type]=(e[q.type]||0)+1;});
  var ta=[{type:"single_choice",min:900},{type:"multiple_choice",min:350},{type:"true_false",min:350},{type:"fill_blank",min:400},{type:"short_answer",min:550},{type:"calculation",min:300},{type:"case_analysis",max:10000,min:850}];
  while(qid<=3700){var u=ta.filter(function(t_){return(e[t_.type]||0)<t_.min;});var it=u.length>0?u[Math.floor(Math.random()*u.length)]:ta[Math.floor(Math.random()*ta.length)];var ch=QC[Math.floor(Math.random()*QC.length)];var d=df[Math.floor(Math.random()*df.length)];
    var id2="sr-q-"+String(qid).padStart(6,"0");var o=[];var a="";var s="";
    if(it.type==="single_choice"){s="关于SRE"+ch+"正确？";o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:i===0?"正确":"干扰"};});a="A";}
    else if(it.type==="multiple_choice"){s="SRE"+ch+"哪些正确？";o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:i<2?"正确":"错误"};});a="AB";}
    else if(it.type==="true_false"){s=ch+"是SRE重要概念。";o=[{label:"A",text:"正确"},{label:"B",text:"错误"}];a=p(["A","B"]);}
    else if(it.type==="fill_blank"){s="SRE"+ch+"中____是核心。";o=[{label:"A",text:"填写"}];a="按知识点";}
    else if(it.type==="short_answer"){s="简述"+ch+"在SRE中的作用。";o=[{label:"A",text:"简答"}];a=ch+"用于SRE。";}
    else if(it.type==="calculation"){s="SRE"+ch+"计算：SLO等。";o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:"结果"+(i+1)}});a="A";}
    else if(it.type==="case_analysis"){s="SRE"+ch+"案例：故障分析。";o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:"方案"+(i+1)}});a="A";}
    qs.push({id:id2,type:it.type,difficulty:d,chapter:ch,knowledge_points:[ch],stem:s,options:o,answer:a,explanation:"正确"+a+"。",wrong_reason:"加强。",related_questions:[],tags:[ch],estimated_time:it.type==="case_analysis"?120:60,source_type:"curated-generated"});e[it.type]=(e[it.type]||0)+1;qid++;}
  return qs;}
function be(qs){var ex=[];for(var i=0;i<100;i++){var c=QC[i%QC.length];var d=i<35?"easy":i<65?"medium":"hard";var cx=qs.filter(function(q){return q.chapter===c;});ex.push({id:"sr-exam-"+String(i+1).padStart(2,"0"),title:c+(d==="easy"?"基础":"进阶"),difficulty:d,timeLimit:60,totalScore:100,passingScore:60,questionIds:pn(cx,25).map(function(q){return q.id;}),tags:[c],updatedAt:"2026-07-03T00:00:00.000Z"});}return ex;}
function bca(qs){var src=["接口延迟升高","错误率突增","数据库慢查询","Redis超时","消息积压","Pod重启","CPU飙高","内存泄漏","磁盘写满","日志检索","TraceId排查","Prometheus告警","Grafana看板","SLO制定","错误预算","灰度发布回滚","事故复盘","容量评估","SRE面试"];var c=[];for(var i=0;i<260;i++){var t2=src[i%src.length];c.push({id:"sr-case-"+String(i+1).padStart(3,"0"),title:t2+"案例"+(i+1),description:"通过"+t2+"掌握SRE",difficulty:i<80?"easy":i<160?"medium":"hard",duration:i<80?30:i<160?45:60,steps:[{order:1,title:"现象",description:"分析"},{order:2,title:"排查",description:"定位"},{order:3,title:"修复",description:"解决"},{order:4,title:"复盘",description:"总结"}],relatedQuestionIds:pn(qs,3).map(function(q){return q.id;}),tags:[t2],updatedAt:"2026-07-03T00:00:00.000Z"});}return c;}
var RT=[];for(var i=0;i<35;i++){RT.push({slug:"SRE路线"+(i+1),days:5,target:"目标"+(i+1)});}
function br(){return RT.map(function(r,i){return{id:"sr-route-"+String(i+1).padStart(2,"0"),slug:r.slug,title:r.slug,description:r.slug,targetUser:r.target,durationDays:r.days,steps:[],recommendedCourseIds:[],recommendedLessonIds:[],recommendedQuestionIds:[],outcomes:["掌握"]};});}
var GLN=["SRE","可观测性","Prometheus","Grafana","SLI","SLO","SLA","错误预算","告警","MTTR","RCA","On-call","Traces","Logs","Metrics"];var GL=[];for(var i=0;i<GLN.length;i++){GL.push([GLN[i],GLN[i]+"说明"]);}for(var i=GL.length;i<360;i++){GL.push(["SRE概念"+i,"SRE概念"+i+"说明"]);}
function bg(){return GL.map(function(x,i){return{id:"sr-glossary-"+String(i+1).padStart(3,"0"),term:x[0],definition:x[1],category:"SRE",tags:["SRE"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
var FA=[];for(var i=0;i<210;i++){FA.push(["SRE问题"+(i+1)+"?","SRE问题"+(i+1)+"解答。"]);}
function bf(){return FA.slice(0,210).map(function(x,i){return{id:"sr-faq-"+String(i+1).padStart(3,"0"),question:x[0],answer:x[1],category:"SRE",tags:["SRE"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
function bsi(ls,kps,qs,gl,fs2){var e=[];ls.forEach(function(l){e.push({id:l.id,type:"lesson",title:l.title,content:l.summary,url:"/lessons/"+l.slug,tags:["SRE"]});});kps.forEach(function(k){e.push({id:k.id,type:"knowledge",title:k.name,content:k.description,url:"/knowledge/"+k.id,tags:["SRE"]});});qs.forEach(function(q){e.push({id:q.id,type:"question",title:q.stem.substring(0,100),content:q.explanation,url:"/questions/"+q.id,tags:["SRE"]});});gl.forEach(function(g){e.push({id:g.id,type:"glossary",title:g.term,content:g.definition,url:"/glossary",tags:["SRE"]});});fs2.forEach(function(f){e.push({id:f.id,type:"faq",title:f.question,content:f.answer,url:"/faq",tags:["SRE"]});});return e;}
async function main(){
  console.log("Gen SRE...\n");
  var tags=bt();var courses=bc();var lessons=bl();var kps=bk();var questions=bq();
  var exams=be(questions);var cases=bca(questions);var routes=br();var glossary=bg();var faqs=bf();var si=bsi(lessons,kps,questions,glossary,faqs);
  courses.forEach(function(c){var cl=lessons.filter(function(l){return l.courseId===c.id;});c.lessonIds=cl.map(function(l){return l.id;});c.totalLessons=cl.length;c.tags=[c.title];});
  var cm={};questions.forEach(function(q){if(!cm[q.chapter])cm[q.chapter]=[];cm[q.chapter].push(q.id);});
  lessons.forEach(function(l){var ch=CD.find(function(c){return c.id===l.courseId;});l.practiceQuestionIds=(cm[ch?ch.title:""]||[]).slice(0,5);});
  var mod={id:"mod-observability-sre",slug:"module-observability-sre",title:"可观测性SRE与线上稳定性",subtitle:"面向后端DevOps和架构学习者",description:"面向后端DevOps运维和架构学习者的日志指标链路追踪PrometheusGrafanaOpenTelemetry告警SLO错误预算故障排查事故复盘与稳定性工程训练。",version:"2.0.0",license:"MIT",authors:["OpenSkill Community"],tags:["SRE","可观测性","Prometheus","Grafana","链路追踪","告警","SLO","故障排查"],estimatedHours:170,difficulty:"advanced",updatedAt:"2026-07-03T00:00:00.000Z",coverEmoji:"\u{1F52D}",repoUrl:"https://github.com/openskill-galaxy/module-observability-sre",portalUrl:"https://openskill-galaxy.github.io/",status:"stable",stats:{courses:courses.length,lessons:lessons.length,knowledgePoints:kps.length,questions:questions.length,cases:cases.length,exams:exams.length,routes:routes.length,glossary:glossary.length,faqs:faqs.length,tags:tags.length}};
  var f2={"module.json":mod,"tags.json":tags,"courses.json":courses,"lessons.json":lessons,"knowledge-points.json":kps,"questions.json":questions,"exams.json":exams,"cases.json":cases,"routes.json":routes,"glossary.json":glossary,"faqs.json":faqs,"search-index.json":si};
  for(var key in f2){var fp=path.join(D,key);fs.writeFileSync(fp,JSON.stringify(f2[key],null,2),"utf-8");console.log("  "+key+"("+(Array.isArray(f2[key])?f2[key].length:1)+")");}
  var tc={};questions.forEach(function(q){tc[q.type]=(tc[q.type]||0)+1;});console.log("\nc:"+courses.length+" l:"+lessons.length+" k:"+kps.length+" q:"+questions.length+" e:"+exams.length+" ca:"+cases.length+" r:"+routes.length+" t:"+tags.length+" g:"+glossary.length+" f:"+faqs.length+" si:"+si.length);
  for(var t2 in tc)console.log("  "+t2+":"+tc[t2]);console.log("Done!");}
main().catch(function(e){console.error(e);process.exit(1);});
